import type {Metadata} from "next";
import "./globals.css";
import {Inter as FontSans} from "next/font/google";
import {cn} from "@/lib/utils";
import {Toaster} from "sonner";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {ThemeProvider} from "@/components/theme-provider";
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased flex items-center flex-col",
          fontSans.variable
        )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <div className="flex-none py-2 text-xl flex gap-2">
            <Toaster />
          </div>
          <div className="flex-1 flex items-center">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
